# Generated by Django 4.2.3 on 2023-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='Default category', help_text='category name', max_length=64, unique=True),
        ),
    ]
